"""Run the faceless-Reel flow end to end.

    python -m src.generate.run                       # hardcoded demo (no shot-list spend)
    python -m src.generate.run --script input/scripts/foo.md
    python -m src.generate.run --script foo.md --dry-run

With --script, Claude generates the shot list (spend-logged, validated,
max 2 attempts). Without it, the hardcoded DEMO_SCRIPT/DEMO_SHOTS run.
Flow: validate -> TTS (cached by script) -> forced alignment (local, free)
-> Pexels footage + vision picks -> ffmpeg assembly -> one .mp4.
--dry-run validates the toolchain and prints estimates without spending.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
import time
from pathlib import Path

from ..lib import align, spend, tts
from ..lib.media import find_ffmpeg
from ..review.qc import review_reel
from .assemble import assemble_reel, shot_boundaries
from .footage import resolve_stock_shots
from .shots import DEMO_SCRIPT, DEMO_SHOTS, generate_shot_list, validate_shot_list


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--script", default=None, help="path to a script file (.md/.txt)")
    parser.add_argument("--out", default=None, help="output mp4 (default: output/<name>.mp4)")
    parser.add_argument("--workdir", default=None, help="default: build/<name>")
    parser.add_argument("--provider", default=None, help="gemini | sapi (default: auto)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    if args.script:
        script_path = Path(args.script)
        script = " ".join(script_path.read_text(encoding="utf-8").split())
        name = script_path.stem
        shots = None  # generated by Claude after the free validations pass
    else:
        script, shots, name = DEMO_SCRIPT, DEMO_SHOTS, "demo_reel"
    out_path = Path(args.out or f"output/{name}.mp4")
    workdir = Path(args.workdir or f"build/{name}")

    # 1. validate everything free before any paid call (fail loudly, cheaply)
    word_count = len(script.split())
    if not 40 <= word_count <= 120:
        print(
            f"ERROR: script is {word_count} words; a ~30s Reel needs roughly 60-90. "
            "Rewrite the script before spending."
        )
        return 1
    if not os.environ.get("PEXELS_API_KEY"):
        print("ERROR: PEXELS_API_KEY is not set (free key at pexels.com/api).")
        return 1
    if shots is None and not os.environ.get("ANTHROPIC_API_KEY"):
        print("ERROR: --script needs ANTHROPIC_API_KEY for shot-list generation.")
        return 1
    find_ffmpeg()
    provider = tts.get_tts_provider(args.provider)

    est_tts = (
        len(script) / 1000 * tts.GEMINI_COST_PER_1K_CHARS
        if isinstance(provider, tts.GeminiTTS)
        else 0.0
    )
    est_shotlist = 0.02 if shots is None else 0.0
    print(f"script: {len(script)} chars, {word_count} words -> {name}")
    print(
        f"estimated cost: ${est_shotlist:.3f} shot list + ${est_tts:.3f} TTS "
        f"+ ~$0.02 vision picks (tts: {provider.name})"
    )
    if args.dry_run:
        print("dry run: validation passed, nothing spent, nothing rendered.")
        return 0

    workdir.mkdir(parents=True, exist_ok=True)

    # 2. shot list (Claude, paid, validated with retry cap) — or the free demo list
    if shots is None:
        t0 = time.time()
        shots = generate_shot_list(script)
        kinds = ", ".join(
            f"{k}x{sum(1 for s in shots if s.kind == k)}"
            for k in dict.fromkeys(s.kind for s in shots)
        )
        print(f"shot list: {len(shots)} shots ({kinds}) in {time.time() - t0:.1f}s")
    validate_shot_list(script, shots)
    stock_count = sum(1 for s in shots if s.kind == "STOCK")

    # 3. voice — cached by (provider, script) so retries never re-pay TTS
    t0 = time.time()
    audio_path = workdir / "voiceover.wav"
    hash_path = workdir / "voiceover.sha"
    script_hash = hashlib.sha256(f"{provider.name}:{script}".encode()).hexdigest()
    if audio_path.exists() and hash_path.exists() and hash_path.read_text() == script_hash:
        wav_bytes, timings = audio_path.read_bytes(), None
        print("voiceover: reused cached audio (no TTS spend)")
    else:
        wav_bytes, timings = provider.synthesize(script)
        audio_path.write_bytes(wav_bytes)
        hash_path.write_text(script_hash)
        print(f"voiceover: synthesized in {time.time() - t0:.1f}s")
    duration = tts.wav_duration_seconds(wav_bytes)
    print(f"voiceover duration: {duration:.1f}s")

    # 4. align (skipped when the provider returns native timings, e.g. ElevenLabs)
    if timings is None:
        t0 = time.time()
        timings = align.align(audio_path, script)
        print(f"alignment: {len(timings)} words ({time.time() - t0:.1f}s, local, free)")
    if not align.check_alignment(timings, script):
        print("ERROR: alignment sanity check failed; not spending time on assembly")
        return 1

    # 5. footage: Pexels search -> vision pick -> download (cached)
    t0 = time.time()
    stock_clips = resolve_stock_shots(shots, workdir)
    print(f"footage: {len(stock_clips)}/{stock_count} stock clips ({time.time() - t0:.1f}s)")

    # 6. assemble
    t0 = time.time()
    out = assemble_reel(
        script, shots, timings, audio_path, duration, out_path, workdir,
        stock_clips=stock_clips,
    )
    boundaries = shot_boundaries(script, shots, timings, duration)
    print(f"assembled: {out} ({time.time() - t0:.1f}s)")
    print(f"  {len(boundaries)} shots, {boundaries[-1][1]:.1f}s total, "
          f"{out.stat().st_size / 1e6:.1f} MB")

    # 7. review — technical checks free, then Claude vision QC
    review = review_reel(out, script, boundaries[-1][1], workdir)
    (workdir / "review.json").write_text(review.to_json(), encoding="utf-8")
    if review.passed:
        print("review: PASSED")
    else:
        print("review: FAILED — flagged for human attention:")
        for issue in review.issues:
            print(f"  - {issue}")
    print(f"total spend (all runs, from spend_log.jsonl): ${spend.total_spend():.4f}")
    return 0 if review.passed else 2  # 2 = built but flagged; the file stays on disk


if __name__ == "__main__":
    sys.exit(main())
